/**
 * Demo seeding — populates the store with realistic back-dated case history,
 * completed sample traces (exported by the ML pipeline), alerts and an NCRP
 * complaint queue so the console is populated on first boot.
 */
import * as fs from "fs";
import * as path from "path";
import { Store } from "./db";

const SEEDS_DIR = path.resolve(__dirname, "..", "seeds");

function loadSeed(file: string): any {
  try {
    return JSON.parse(fs.readFileSync(path.join(SEEDS_DIR, file), "utf-8"));
  } catch {
    return null;
  }
}

// Cryptographically valid demo addresses (generated by
// apps/ml/scripts/make_demo_wallets.py) — rotated per seeded record.
const VALID_DEMO: Record<string, string[]> = {
  BTC: [
    "1657TAVscUsbzmvf52x8X9APgfTPndrsNE",
    "3BeTSPDF6hxhmaqazmWYMrVKJPHXdmsXns",
    "bc1qe36w2wz9828z567vlw5r4zv0f39p5wetpge6tl",
  ],
  ETH: ["0x7358e2aB59D4A01EDfE1CC52f410316131669e20"],
  TRON: ["TJLKnZKEWM2VdTqXhUK8LWG1cQ4uHBBurn", "TDCuLsMKR7cY9rFzYQEufFZMX9yK4RvLXM"],
};

function simAddress(chain: string, i: number): string {
  const pool = VALID_DEMO[chain] || VALID_DEMO.BTC;
  return pool[i % pool.length];
}

const STATES = ["Maharashtra", "Uttar Pradesh", "Karnataka", "Delhi", "Gujarat",
  "Tamil Nadu", "West Bengal", "Rajasthan", "Telangana", "Bihar"];

const SAMPLE_TITLES: Record<string, string> = {
  investment: "Investment scam — TRON USDT peel chain",
  sextortion: "Sextortion — BTC mixer pass to exchange",
  task: "Task-based fraud — ETH dust fan-in",
  ransomware: "Ransomware — BTC consolidation to exchange",
};

export function seedIfEmpty(store: Store, opts: { force?: boolean } = {}): void {
  const t = store.tables as any;
  if (!opts.force && t.cases.length > 0) return;
  if (opts.force) {
    t.cases.length = 0; t.traces.length = 0; t.alerts.length = 0;
    t.ncrpQueue.length = 0; t.sahyogOutbox.length = 0;
  }

  const history = loadSeed("history.json")?.history ?? [];
  const traces = loadSeed("traces.json")?.traces ?? {};
  const now = Date.now();

  // ---- historical case records (dashboard analytics) ----
  history.forEach((h: any, i: number) => {
    const chain = h.chain;
    t.cases.push({
      id: `case-hist-${i}`,
      reference: `TRX/2026/${String(1000 + i)}`,
      title: `${h.category} — ${chain} wallet`,
      status: h.attributedVasp ? (i % 4 === 0 ? "CLOSED" : "ATTRIBUTED") : "OPEN",
      priority: h.riskLevel === "CRITICAL" ? "P1" : h.riskLevel === "HIGH" ? "P2" : "P3",
      complaint: {
        id: `ncrp-seed-${i}`,
        cen: `CEN-2026-${String(200000 + i * 37)}`,
        category: h.category,
        amountUsd: Math.round((h.riskScore * 137) % 42000 + 300),
        state: STATES[i % STATES.length],
        reportedAt: h.at,
        complainantAlias: `Complainant #${30000 + i * 11}`,
        suspectAddresses: [{ address: simAddress(chain, i), chain }],
        source: "NCRP seed",
      },
      createdBy: i % 3 === 0 ? "supervisor" : "investigator",
      createdAt: h.at,
      updatedAt: h.at + (h.durationMs || 3000),
      traceIds: [],
      latestTraceId: null,
      riskScore: h.riskScore,
      riskLevel: h.riskLevel,
      attributedVasp: h.attributedVasp,
      audit: [
        { id: `aud-${i}-1`, at: h.at, actor: "ncrp-sync", action: "CASE_CREATED",
          detail: `Imported from NCRP (${h.category})` },
        { id: `aud-${i}-2`, at: h.at + 1200, actor: "SYSTEM", action: "TRACE_COMPLETED",
          detail: `Historic trace — risk ${h.riskScore} ${h.riskLevel}` },
      ],
    });
  });

  // ---- featured completed traces from the ML export ----
  Object.entries(traces).forEach(([key, result]: [string, any], idx) => {
    const completedAt = now - (idx + 1) * 36e5 * 5;
    const traceId = `trc-seed-${key}`;
    const caseId = `case-featured-${key}`;
    const riskLevel = result?.risk?.level ?? "HIGH";
    const primary = result?.primaryAttribution;
    const chain = result?.chain ?? "BTC";

    t.traces.push({
      id: traceId,
      caseId,
      seedAddress: result?.seedAddress,
      chain,
      typologyHint: result?.risk?.typology ?? null,
      status: "COMPLETED",
      stage: "DONE",
      detail: "Trace complete",
      progress: 100,
      startedAt: result?.startedAt ?? completedAt - 4000,
      completedAt: result?.completedAt ?? completedAt,
      durationMs: result?.durationMs ?? 4000,
      mode: result?.mode ?? "simulated",
      result,
    });

    t.cases.unshift({
      id: caseId,
      reference: `TRX/2026/${900 + idx}`,
      title: SAMPLE_TITLES[key] ?? `Demo scenario — ${key}`,
      status: primary ? "ATTRIBUTED" : "TRACING",
      priority: riskLevel === "CRITICAL" ? "P1" : "P2",
      complaint: {
        id: `ncrp-featured-${key}`,
        cen: `CEN-2026-9${String(10000 + idx * 137)}`,
        category: (result?.risk?.typology ?? "UNKNOWN").replace("_", " ").toLowerCase(),
        amountUsd: result?.summary?.totalValueUsd ?? 5000,
        state: STATES[(idx + 2) % STATES.length],
        reportedAt: completedAt - 36e5 * 30,
        complainantAlias: `Complainant #9${1000 + idx}`,
        suspectAddresses: [{ address: result?.seedAddress, chain }],
        source: "NCRP featured",
      },
      createdBy: idx % 2 === 0 ? "investigator" : "supervisor",
      createdAt: completedAt - 36e5 * 30,
      updatedAt: completedAt,
      traceIds: [traceId],
      latestTraceId: traceId,
      riskScore: result?.risk?.score ?? null,
      riskLevel,
      attributedVasp: primary?.name ?? null,
      audit: [
        { id: `aud-f-${idx}-1`, at: completedAt - 36e5 * 30, actor: "ncrp-sync",
          action: "CASE_CREATED", detail: "Imported from NCRP" },
        { id: `aud-f-${idx}-2`, at: completedAt, actor: "SYSTEM", action: "TRACE_COMPLETED",
          detail: primary ? `Attributed to ${primary.name} (${Math.round((primary.confidence ?? 0) * 100)}%)`
                          : "Completed without exchange attribution" },
      ],
    });

    // seed a couple of alerts from featured traces
    if (primary) {
      t.alerts.push({
        id: `alr-seed-${key}`, at: completedAt,
        severity: riskLevel === "CRITICAL" ? "P1" : "P2",
        kind: "VASP_HIT",
        title: `${primary.name} attribution — ${Math.round((primary.confidence ?? 0) * 100)}% confidence`,
        detail: `${SAMPLE_TITLES[key] ?? key}: funds reach ${primary.name} within ${primary.pathDepth} hop(s).`,
        caseId, traceId, chain, vaspName: primary.name,
        acknowledged: idx > 1,
      });
    }
    if ((result?.patterns ?? []).some((p: any) => p.type === "MIXER_PASS")) {
      t.alerts.push({
        id: `alr-seed-${key}-mix`, at: completedAt + 60e3, severity: "P2", kind: "MIXER",
        title: "Mixer pass detected", detail: `${SAMPLE_TITLES[key] ?? key}: funds routed through a mixing service.`,
        caseId, traceId, chain, vaspName: null, acknowledged: false,
      });
    }
  });

  // ---- NCRP queue + SAHYOG outbox samples ----
  t.ncrpQueue.push({
    id: "ncrp-seed-queue-1", cen: "CEN-2026-778211", category: "Phishing",
    amountUsd: 3400, state: "Rajasthan", reportedAt: now - 36e5 * 8,
    complainantAlias: "Complainant #77120",
    suspectAddresses: [{ address: simAddress("TRON", 777), chain: "TRON" }],
    source: "NCRP sandbox", narrative: "Fake exchange login page harvesting deposits.",
  });
  t.sahyogOutbox.push({
    id: "syg-seed-1", at: now - 36e5 * 4, type: "ALERT_PUSH",
    refId: "alr-seed-sextortion", caseId: "case-featured-sextortion",
    chain: "BTC", status: "SENT", body: "P1 mixer pass + exchange attribution — inter-agency coordination requested.",
  });

  t.alerts.push({
    id: "alr-seed-case", at: now - 36e5 * 2, severity: "P3", kind: "CASE_CREATED",
    title: "NCRP complaints pending triage", detail: "1 complaint queued in the NCRP sandbox — review and open a case.",
    caseId: null, traceId: null, chain: null, vaspName: null, acknowledged: false,
  });

  t.cases.sort((a: any, b: any) => b.updatedAt - a.updatedAt);
  t.alerts.sort((a: any, b: any) => b.at - a.at);
  store.flush();
  console.log(`[seed] cases=${t.cases.length} traces=${t.traces.length} alerts=${t.alerts.length}`);
}
